### ISSUE TITLE
Error running social_sample.py

### ISSUE THREAD

**Issue by DanqingZ** [vvanirudh/social-lstm-tf#2]
Hi I have got below error when I ran social_sample.py, but I can successfully run social_train.py. I would really appreciate your help if you take some time to look at this. Many thanks!
```
********************** SAMPLING A NEW TRAJECTORY 0 ******************************
Traceback (most recent call last):
  File "social_sample.py", line 150, in <module>
    main()
  File "social_sample.py", line 130, in main
    complete_traj = model.sample(sess, obs_traj, obs_grid, dimensions, x_batch, sample_args.pred_length)
  File "/Users/danqing0703/Google_Drive/research_2017Spring/TF_Deep_learning/social-lstm-tf-master/social_lstm/social_model.py", line 371, in sample
    [states, cost] = sess.run([self.final_states, self.cost], feed)
  File "/Users/danqing0703/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/Users/danqing0703/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/danqing0703/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/Users/danqing0703/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.FailedPreconditionError: Attempting to use uninitialized value coordinate_embedding/embedding_w
	 [[Node: coordinate_embedding/embedding_w/read = Identity[T=DT_FLOAT, _class=["loc:@coordinate_embedding/embedding_w"], _device="/job:localhost/replica:0/task:0/cpu:0"](coordinate_embedding/embedding_w)]]
Caused by op u'coordinate_embedding/embedding_w/read', defined at:
  File "social_sample.py", line 150, in <module>
    main()
  File "social_sample.py", line 84, in main
    model = SocialModel(saved_args, True)
  File "/Users/danqing0703/Google_Drive/research_2017Spring/TF_Deep_learning/social-lstm-tf-master/social_lstm/social_model.py", line 73, in __init__
    self.define_embedding_and_output_layers(args)
  File "/Users/danqing0703/Google_Drive/research_2017Spring/TF_Deep_learning/social-lstm-tf-master/social_lstm/social_model.py", line 216, in define_embedding_and_output_layers
    self.embedding_w = tf.get_variable("embedding_w", [2, args.embedding_size], initializer=tf.truncated_normal_initializer(stddev=0.1))
  File "/Users/danqing0703/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 339, in get_variable
    collections=collections)
  File "/Users/danqing0703/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 262, in get_variable
    collections=collections, caching_device=caching_device)
  File "/Users/danqing0703/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 158, in get_variable
    dtype=variable_dtype)
  File "/Users/danqing0703/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 209, in __init__
    dtype=dtype)
  File "/Users/danqing0703/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 318, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/Users/danqing0703/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 609, in identity
    return _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/Users/danqing0703/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/Users/danqing0703/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/danqing0703/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()
```

**Comment by DanqingZ** [comment]
I have fixed the problem, sorry that I made a mistake...
